/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.william.calculadora.gui;

import br.com.william.calculadora.logico.Logica;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class CalculadoraGui extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGui
     */
    public CalculadoraGui() {
             
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/br/com/william/calculadora/multimidia/calculator.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        divisao1 = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        painelCalculadora = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        oito = new javax.swing.JButton();
        quatro = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        um = new javax.swing.JButton();
        dois = new javax.swing.JButton();
        divisao = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        sete = new javax.swing.JButton();
        ce = new javax.swing.JButton();
        limpar1 = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        mais = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        sinal = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        divisao1.setText("/");
        divisao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisao1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setPreferredSize(new java.awt.Dimension(300, 280));
        getContentPane().setLayout(null);

        painel.setLayout(new java.awt.CardLayout());

        painelCalculadora.setEditable(false);
        painelCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                painelCalculadoraActionPerformed(evt);
            }
        });
        painel.add(painelCalculadora, "card2");

        getContentPane().add(painel);
        painel.setBounds(0, 10, 290, 30);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });
        jPanel1.add(oito, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 49, -1));

        quatro.setText("4");
        quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroActionPerformed(evt);
            }
        });
        jPanel1.add(quatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 49, -1));

        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });
        jPanel1.add(nove, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 49, -1));

        um.setText("1");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });
        jPanel1.add(um, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 50, -1));

        dois.setText("2");
        dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisActionPerformed(evt);
            }
        });
        jPanel1.add(dois, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 49, -1));

        divisao.setText("/");
        divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisaoActionPerformed(evt);
            }
        });
        jPanel1.add(divisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 49, -1));

        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 49, -1));

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 49, -1));

        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });
        jPanel1.add(sete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 49, -1));

        ce.setText("CE");
        ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceActionPerformed(evt);
            }
        });
        jPanel1.add(ce, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        limpar1.setText("<-");
        limpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar1ActionPerformed(evt);
            }
        });
        jPanel1.add(limpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        jPanel1.add(zero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 50, -1));

        mais.setText("+");
        mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisActionPerformed(evt);
            }
        });
        jPanel1.add(mais, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 50, -1));

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });
        jPanel1.add(menos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 50, -1));

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 49, -1));

        multi.setText("*");
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        jPanel1.add(multi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 50, -1));

        sinal.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        sinal.setText(".");
        sinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinalActionPerformed(evt);
            }
        });
        jPanel1.add(sinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 50, -1));

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        jPanel1.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 50, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 40, 230, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void painelCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painelCalculadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_painelCalculadoraActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.nove.getText());
    }//GEN-LAST:event_noveActionPerformed

    private void ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceActionPerformed
        // TODO add your handling code here:
        this.painelCalculadora.setText("");
    }//GEN-LAST:event_ceActionPerformed

    private void umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umActionPerformed
        // TODO add your handling code here:
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.um.getText());
    }//GEN-LAST:event_umActionPerformed

    private void doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.dois.getText());
    }//GEN-LAST:event_doisActionPerformed

    private void divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisaoActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.divisao.getText());
    }//GEN-LAST:event_divisaoActionPerformed

    private void quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.quatro.getText());
    }//GEN-LAST:event_quatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.cinco.getText());
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.seis.getText());
    }//GEN-LAST:event_seisActionPerformed

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.sete.getText());
    }//GEN-LAST:event_seteActionPerformed

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoActionPerformed
        // TODO add your handling code here:
        
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.oito.getText());
    }//GEN-LAST:event_oitoActionPerformed

    private void limpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar1ActionPerformed
        // TODO add your handling cobde here:
        try{
            StringBuffer strB=new StringBuffer(this.painelCalculadora.getText());
            String tela=new StringBuffer(strB.toString().substring(0,strB.length()-1)).toString();
            this.painelCalculadora.setText(tela);
        }catch(StringIndexOutOfBoundsException e){
            this.painelCalculadora.setText("");
        }
    }//GEN-LAST:event_limpar1ActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
            this.painelCalculadora.setText(this.painelCalculadora.getText()+this.zero.getText());
    
    }//GEN-LAST:event_zeroActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        // TODO add your handling code here:
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.menos.getText());
   
    }//GEN-LAST:event_menosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.tres.getText());
   
    }//GEN-LAST:event_tresActionPerformed

    private void divisao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisao1ActionPerformed
        // TODO add your handling code here:
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.divisao1.getText());
   
    }//GEN-LAST:event_divisao1ActionPerformed

    private void sinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinalActionPerformed
        // TODO add your handling code here:
         this.painelCalculadora.setText(this.painelCalculadora.getText()+this.sinal.getText());
   
    }//GEN-LAST:event_sinalActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.multi.getText());
   
    }//GEN-LAST:event_multiActionPerformed

    private void maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisActionPerformed
        // TODO add your handling code here:
        this.painelCalculadora.setText(this.painelCalculadora.getText()+this.mais.getText());
   
    }//GEN-LAST:event_maisActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
        try{
            String valor;
            valor = Logica.calcula(painelCalculadora.getText());
            this.painelCalculadora.setText(valor);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ce;
    private javax.swing.JButton cinco;
    private javax.swing.JButton divisao;
    private javax.swing.JButton divisao1;
    private javax.swing.JButton dois;
    private javax.swing.JButton igual;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar1;
    private javax.swing.JButton mais;
    private javax.swing.JButton menos;
    private javax.swing.JButton multi;
    private javax.swing.JButton nove;
    private javax.swing.JButton oito;
    private javax.swing.JPanel painel;
    private javax.swing.JTextField painelCalculadora;
    private javax.swing.JButton quatro;
    private javax.swing.JButton seis;
    private javax.swing.JButton sete;
    private javax.swing.JButton sinal;
    private javax.swing.JButton tres;
    private javax.swing.JButton um;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
